### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Maritzaspott** [Maritzaspott/COMP5130-UG1#1]
- [x] Generating a base set @piperbedell 
- [x] Calculating frequency @piperbedell 
- [x] Returning minimum support (pruning) @zrw0007 
- [x] Creating next item sets @zrw0007 
- [x] General apriori function @Maritzaspott  
- [x] Calculating confidence and determining strong association rules @Maritzaspott
